source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'kramdown', '~> 2.4'
gem 'kramdown-parser-gfm', '~> 1.1'
gem 'rake', '~> 13.0'
gem 'thor', '~> 1.3'
gem 'activesupport', '~> 7.0'
gem 'stringex', '~> 2.8'
gem 'webrick', '~> 1.8'